export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const LOADER_REQUEST = "LOADER_REQUEST"
export const LOADER_SUCCESS = "LOADER_SUCCESS"
export const LOADER_FAIL = "LOADER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";